FROM docker.io/library/debian:bullseye-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -o Acquire::Retries=5 -o Acquire::http::Pipeline-Depth=0 \
 && apt-get install -y -o Acquire::Retries=5 -o Acquire::http::Pipeline-Depth=0 --no-install-recommends \
      gcc-9 \
      binutils \
      xz-utils \
      python3-minimal \
      libc6-dev \
      ca-certificates \
 && ln -sf /usr/bin/gcc-9 /usr/local/bin/gcc \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /c_optimizer
